[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["greetingservice"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "greetingservice"
  org = "kapilraajperinpanayagam"
  version = "3.1.1"

